---
- name: Install Tomcat
  hosts: all
  become: yes

  tasks:
  - name: Install Java for RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install Java for Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.73/bin/apache-tomcat-8.5.73.tar.gz
      dest: /opt

  - name: Extract Tomcat Package
    unarchive:
      src: /opt/apache-tomcat-8.5.73.tar.gz
      dest: /opt
      remote_src: yes

  - name: Give executable permissons to startup.sh
    file:
      path : /opt/apache-tomcat-8.5.73/bin/startup.sh
      mode: 0777

  - name: Start the Tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.73/bin/
