---
- name: Playbook to uninstall https and stopping service
  hosts: all
  become: yes

  tasks:
  - name: stop service
    service:
      name: httpd
      state: stopped

  - name: uninstall httpd
    yum:
      name: httpd
      state: absent
